platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'taroDemo' do
  # Pods for HelloWorld
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

   # react-native-maps dependencies
   pod 'react-native-maps', path:'../node_modules/react-native-maps'

  use_unimodules!

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # fix archive error vs Xcode10+
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      if target.name == "yoga"
        target.remove_from_project
      end
    end
  end

  target 'taroDemoTests' do
    inherit! :search_paths
  end
end
